### ISSUE TITLE
Two comics books repack failed

### ISSUE THREAD

**Issue by cldotdev** [Haoyi-Han/Moxmoe-Epub-Manga-Repacker#1] opened 2022-12-22 17:57 UTC
The following two comics books repack failed, resulting in the incorrect page order.

- 藤本樹短篇集 22-26: 人魚狂想曲
- 藤本樹短篇集 22-26: 預言的那由多

![圖片](https://user-images.githubusercontent.com/2265716/209196513-f225cb97-7065-4075-a180-315a407b0a2d.png)

**Comment by Haoyi-Han** [comment] 2022-12-25 11:04
Unexpected ... I'm working on it, thank you for proposing this issue.

**Comment by Haoyi-Han** [comment] 2022-12-25 12:28
Fixed in the latest version.

**Comment by cldotdev** [comment] 2022-12-25 12:35
There's an error for the latest version.

```
============> 开始初始化程序
已完成文件列表抽取。
输入目录为： /mnt/hgfs/Share/moe/repacker
输出目录为： /mnt/hgfs/Share/moe/repacker/output
已完成目录结构复制。
============> 开始提取图片并打包文件
on 0: 开始解析  [Mox][藤本樹短篇集 22-26]人魚狂想曲.kepub
on 0: [藤本樹短篇集 22-26]人魚狂想曲 => 开始提取
Mox.moe |⚠                                       | (!) 0/4 [0%] in 0.5s (0.00/s)
Traceback (most recent call last):
  File "MoeKepub2Cbz.py", line 140, in <module>
    comic_src = loadZipImg(file_t, cachefolder=cachefolder)
  File "MoeKepub2Cbz.py", line 95, in loadZipImg
    html_list: list = htmlExtractToList(extract_dir)
  File "MoeKepub2Cbz.py", line 65, in htmlExtractToList
    soup_0 = BeautifulSoup(volopf.read(), features='xml')
  File "/home/jlhg/.pyenv/versions/3.8.5/lib/python3.8/site-packages/bs4/__init__.py", line 248, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
```

**Comment by Haoyi-Han** [comment] 2022-12-25 14:34
Unfortunately I was unable to reproduce this error using the same comic file. I update the program with an extra packaging, and you can retry if it's going well.

P.S. I notice that you're using Python 3.8. Although this may not be the cause, I recommend that you switch to Python 3.9 and retry. (This program also tests well on Python 3.8 on my side)

**Comment by cldotdev** [comment] 2022-12-25 15:09
Installing lxml package can resolve that issue:

```
pip install lxml
```

Maybe you can add `lxml==4.9.2` to the requirements.txt file.

**Comment by Haoyi-Han** [comment] 2022-12-25 15:20
Very useful advice. I updated the requirement.txt file. Thanks.

**Closed as completed** 2022-12-26 02:52 UTC
Labels: bug, good first issue
